package Form.Client;

import BO.Client.ClientWiseCPTGroup;
import Controller.Client.ClientCPTPackagesController;
import TableModel.Client.ClientWisePackagesDetailTableModel;
import TableModel.Client.ClientWisePackagesTableModel;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import utilities.Constants;
import utilities.Database;
import utilities.DefinitionTypes;
import utilities.DisplayLOV;

public class ClientCPTPackages extends javax.swing.JInternalFrame {

    List<ClientWiseCPTGroup> listClientGroups = new ArrayList();
    List<ClientWiseCPTGroup> listClientGroupCPT = new ArrayList();
    ClientWiseCPTGroup objPkg = new ClientWiseCPTGroup();
    ClientWiseCPTGroup objPkgDetail = new ClientWiseCPTGroup();
    DisplayLOV lov = new DisplayLOV();
    ClientCPTPackagesController ctlClientCPTPackage = new ClientCPTPackagesController();
    private String clientId = "";
    private String packageId = "";

    public ClientCPTPackages() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnExitAssign = new javax.swing.JButton();
        pnlPatientDetail = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGroupDetail = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtSrchCPT = new javax.swing.JTextField();
        btndeleteMember = new javax.swing.JButton();
        groupName = new javax.swing.JLabel();
        txtSrchClient = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblGroupNames = new javax.swing.JTable();
        txtPackage = new javax.swing.JTextField();
        Search = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(Constants.red , Constants.green , Constants.black));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(Constants.title+"Client Wise Packages");
        setFrameIcon(null);

        jPanel12.setBackground(new java.awt.Color(Constants.red , Constants.green , Constants.black));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));

        btnClear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExitAssign.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExitAssign.setForeground(new java.awt.Color(102, 0, 0));
        btnExitAssign.setText("Exit");
        btnExitAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnExitAssign)
                .addComponent(btnClear))
        );

        pnlPatientDetail.setBackground(new java.awt.Color(Constants.red , Constants.green , Constants.black));
        pnlPatientDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Wise CPT Packages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(102, 0, 0))); // NOI18N
        pnlPatientDetail.setForeground(java.awt.SystemColor.activeCaption);

        jPanel6.setBackground(new java.awt.Color(Constants.red , Constants.green , Constants.black));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Package Wise Services", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N

        tblGroupDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {null, null}
            },
            new String [] {
                "Group Name", "Parameter"
            }
        ));
        tblGroupDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupDetailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblGroupDetailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblGroupDetailMouseReleased(evt);
            }
        });
        tblGroupDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblGroupDetailKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tblGroupDetail);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Select Service : ");

        txtSrchCPT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSrchCPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSrchCPTActionPerformed(evt);
            }
        });

        btndeleteMember.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndeleteMember.setText("Delete");
        btndeleteMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btndeleteMemberMouseReleased(evt);
            }
        });
        btndeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteMemberCreate_User(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSrchCPT, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeleteMember)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSrchCPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeleteMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
        );

        groupName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        groupName.setForeground(new java.awt.Color(102, 0, 0));
        groupName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        groupName.setText("Select  Client : ");

        txtSrchClient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSrchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSrchClientActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveMouseReleased(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCreate_User(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(Constants.red , Constants.green , Constants.black));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(102, 0, 0))); // NOI18N

        tblGroupNames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {null, null, null}
            },
            new String [] {
                "Sr.", "Group Name", "CRTD BY"
            }
        ));
        tblGroupNames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupNamesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblGroupNamesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblGroupNamesMouseReleased(evt);
            }
        });
        tblGroupNames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblGroupNamesKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tblGroupNames);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        txtPackage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackageActionPerformed(evt);
            }
        });

        Search.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(102, 0, 0));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Search.setText("Search Package : ");

        btnDelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCreate_User(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCreate_User(evt);
            }
        });

        javax.swing.GroupLayout pnlPatientDetailLayout = new javax.swing.GroupLayout(pnlPatientDetail);
        pnlPatientDetail.setLayout(pnlPatientDetailLayout);
        pnlPatientDetailLayout.setHorizontalGroup(
            pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPatientDetailLayout.createSequentialGroup()
                .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlPatientDetailLayout.createSequentialGroup()
                        .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPatientDetailLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(groupName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlPatientDetailLayout.createSequentialGroup()
                                        .addComponent(txtPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtSrchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(9, 9, 9)))
                .addGap(19, 19, 19))
        );
        pnlPatientDetailLayout.setVerticalGroup(
            pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPatientDetailLayout.createSequentialGroup()
                .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSrchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPatientDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPatientDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPatientDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAssignActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnExitAssignActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clear();

    }//GEN-LAST:event_btnClearActionPerformed

    private void tblGroupDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupDetailMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupDetailMouseClicked

    private void tblGroupDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupDetailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupDetailMousePressed

    private void tblGroupDetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupDetailMouseReleased

        objPkgDetail = listClientGroupCPT.get(tblGroupDetail.getSelectedRow());
        objPkg.setCptId(objPkgDetail.getCptId());
    }//GEN-LAST:event_tblGroupDetailMouseReleased

    private void tblGroupDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblGroupDetailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupDetailKeyReleased

    private void txtSrchCPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSrchCPTActionPerformed
        if (listClientGroups.isEmpty()) {
            return;
        }
        String query = "SELECT CPT_ID ID, DESCRIPTION FROM  \n"
                + Database.DCMS.CPT + "                     \n"
                + " WHERE UPPER(DESCRIPTION) LIKE '%"
                + txtSrchCPT.getText().trim().toUpperCase() + "%'\n"
                + " AND CPT_ID NOT IN (SELECT CPT_ID FROM "+Database.DCMS.cptPackageDetail+""
                + "WHERE PACKAGE_ID = '"+ objPkg.getPackageId() +"')"
                + "AND ACTIVE = 'Y'                         \n";

        lov.LOVSelection(query, this);
        if (Constants.lovID.equalsIgnoreCase("ID")) {
            clientId = "";
            return;
        }
        System.out.println("CPT ID: "+ Constants.lovID);
        objPkg.setCptId(Constants.lovID);
        txtSrchCPT.setText("");
        if(ctlClientCPTPackage.addPackageDetail(objPkg)){
            listClientGroupCPT = ctlClientCPTPackage.selectClientWisePackageDetail(
                objPkg.getPackageId(), "");
        selectClientWiseGroupDetail();
        }else{
            JOptionPane.showMessageDialog(null, "Unable to add CPT.");
        }
        

    }//GEN-LAST:event_txtSrchCPTActionPerformed

    private void btndeleteMemberMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMemberMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteMemberMouseReleased

    private void btndeleteMemberCreate_User(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteMemberCreate_User

        if (listClientGroupCPT.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kindly Select Package to Delete CPT.");
            txtPackage.requestFocusInWindow();
            return;
        }
        if(objPkg.getCptId().length() == 0){
            JOptionPane.showMessageDialog(null, "There is no CPT to Delete in Package.\n"
                    + "Please add CPT in the Package.");
            txtSrchCPT.requestFocusInWindow();
            return;
        }
        int confirmation = JOptionPane.showConfirmDialog(null, "You Are Going "
                + "To Delete the CPT. \nDo you want to Delete?");
        if (confirmation != 0) {
            return;
        }
        if (ctlClientCPTPackage.deletePackageDetail(objPkg)) {
            JOptionPane.showMessageDialog(null, "Package Delete Successfully.");
            listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId, "");
            selectClientWiseGroups();
        } else {
            JOptionPane.showMessageDialog(null, "Unable to Delete.\n"
                    + "Kindly contact Administrator.");
        }
    }//GEN-LAST:event_btndeleteMemberCreate_User

    private void txtSrchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSrchClientActionPerformed
        String query = "SELECT ID, DESCRIPTION FROM                \n"
                + Database.DCMS.client + "                         \n"
                + " WHERE UPPER(DESCRIPTION) LIKE '%"
                + txtSrchClient.getText().trim().toUpperCase() + "%' \n"
                + " AND ACTIVE = 'Y'";

        lov.LOVSelection(query, this);
        if (Constants.lovID.equalsIgnoreCase("ID")) {
            clientId = "";
            return;
        }
        clientId = Constants.lovID;
        objPkg.setClientId(clientId);
        txtSrchClient.setText(Constants.lovDescription);
        listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId, "");
        selectClientWiseGroups();
        txtPackage.requestFocus();
    }//GEN-LAST:event_txtSrchClientActionPerformed

    private void btnSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseReleased

    private void btnSaveCreate_User(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCreate_User

        if (txtSrchClient.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Kindly select Client to Add Group.");
            txtSrchClient.requestFocusInWindow();
            return;
        }
        if (ctlClientCPTPackage.addNewPackage(objPkg)) {
            JOptionPane.showMessageDialog(null, "Group Save Successfully.");
            listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId, "");
            selectClientWiseGroups();
        } else {
            JOptionPane.showMessageDialog(null, "Unable to save.\n"
                    + "Kindly contact Administrator.");
        }
    }//GEN-LAST:event_btnSaveCreate_User

    private void tblGroupNamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupNamesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupNamesMouseClicked

    private void tblGroupNamesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupNamesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupNamesMousePressed

    private void tblGroupNamesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupNamesMouseReleased

        if (tblGroupNames.getSelectedRow() < 0 || listClientGroups.isEmpty()) {
            return;
        }
        objPkg = listClientGroups.get(tblGroupNames.getSelectedRow());
        txtPackage.setText(objPkg.getPackageDescription());
        listClientGroupCPT = ctlClientCPTPackage.selectClientWisePackageDetail(objPkg.getPackageId(), "");
        selectClientWiseGroupDetail();


    }//GEN-LAST:event_tblGroupNamesMouseReleased

    private void tblGroupNamesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblGroupNamesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGroupNamesKeyReleased

    private void txtPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackageActionPerformed
        
        String query = "SELECT ID, DESCRIPTION FROM                 \n"
                + Database.DCMS.definitionTypeDetail + "            \n"
                + " WHERE UPPER(DESCRIPTION) LIKE '%"
                + txtPackage.getText().trim().toUpperCase() + "%'   \n"
                + "AND DEF_TYPE_ID = "+ DefinitionTypes.packages +" \n"
                + "AND ID NOT IN (SELECT PACKAGE_ID FROM "
                +Database.DCMS.clientWisePackage+" "
                + "WHERE CLIENT_ID = "+clientId+" )"
                + "AND ACTIVE = 'Y'                                 \n";

        lov.LOVSelection(query, this);
        if (Constants.lovID.equalsIgnoreCase("ID")) {
            clientId = "";
            return;
        }
        objPkg.setPackageId(Constants.lovID);
        txtPackage.setText(Constants.lovDescription);
        
//        listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId,
//                objPkg.getPackageId());
//        selectClientWiseGroups();


    }//GEN-LAST:event_txtPackageActionPerformed

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnDeleteCreate_User(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCreate_User
        if (txtPackage.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Kindly Select Package to Delete.");
            txtPackage.requestFocusInWindow();
            return;
        }
        int confirmation = JOptionPane.showConfirmDialog(null, "You Are Going "
                + "To Delete the Package ("+objPkg.getPackageDescription()
                +"). \nDo you want to Delete?");
        if (confirmation != 0) {
            return;
        }
        if (ctlClientCPTPackage.deletePackage(objPkg)) {
            JOptionPane.showMessageDialog(null, "Package Delete Successfully.");
            clear();
            listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId, "");
            selectClientWiseGroups();
        } else {
            JOptionPane.showMessageDialog(null, "Unable to Delete.\n"
                    + "Kindly contact Administrator.");
        }
    }//GEN-LAST:event_btnDeleteCreate_User

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnEditCreate_User(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCreate_User
        // TODO add your handling code here:
        if (txtPackage.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Kindly Select Package to Edit.");
            txtPackage.requestFocusInWindow();
            return;
        }
        int confirmation = JOptionPane.showConfirmDialog(null, "You Are Going "
                + "To Update the Package ("+objPkg.getPackageDescription()
                +") to ("+txtPackage.getText().trim().toUpperCase()+"). "
                        + "\nDo you want to Edit?");
        if (confirmation != 0) {
            return;
        }
        objPkg.setPackageDescription(txtPackage.getText().trim().toUpperCase());
        if (ctlClientCPTPackage.updatePackageName(objPkg)) {
            JOptionPane.showMessageDialog(null, "Package Edit Successfully.");
            clear();
            listClientGroups = ctlClientCPTPackage.selectClientWisePackage(clientId, "");
            selectClientWiseGroups();
        } else {
            JOptionPane.showMessageDialog(null, "Unable to Edit.\n"
                    + "Kindly contact Administrator.");
        }
    }//GEN-LAST:event_btnEditCreate_User


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExitAssign;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btndeleteMember;
    private javax.swing.JLabel groupName;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pnlPatientDetail;
    private javax.swing.JTable tblGroupDetail;
    private javax.swing.JTable tblGroupNames;
    private javax.swing.JTextField txtPackage;
    private javax.swing.JTextField txtSrchCPT;
    private javax.swing.JTextField txtSrchClient;
    // End of variables declaration//GEN-END:variables

    public void clear() {

        txtSrchClient.setText("");
        txtSrchCPT.setText("");
        txtPackage.setText("");
        listClientGroupCPT.clear();
        listClientGroups.clear();
        tblGroupDetail.setModel(new ClientWisePackagesDetailTableModel(listClientGroupCPT));
        tblGroupNames.setModel(new ClientWisePackagesTableModel(listClientGroups));
//        tblGroupNames.setModel(new UsersGroupTableModel(listClientGroups));
//        tblParameter.setModel(new GroupWiseParameterTableModel(listGroupParameter));
    }

//    private void selectGroups() {
//
//        tblGroupNames.addRowSelectionInterval(0, 0);
//        ListSelectionModel selectionModel = tblGroupNames.getSelectionModel();
//        tblGroupNames.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        setColumnsWidthsCwUModel();
//        selectionModel.setSelectionInterval(0, 0);
//        Constants.tablelook.setJTableEnvironment(tblGroupNames);
//
//    }
//
//    public void setColumnsWidthsCwUModel() {
//        TableColumn column = null;
//        for (int i = 0; i < tblGroupNames.getColumnCount(); i++) {
//            column = tblGroupNames.getColumnModel().getColumn(i);
//            if (i == 0) {
//                column.setPreferredWidth(10);
//            } else if (i == 1) {
//                column.setPreferredWidth(300);
//            } else {
//                column.setPreferredWidth(300);
//            }
//        }
//    }
    public void setColumnsWidthsCwUModell() {
        TableColumn column = null;
        for (int i = 0; i < tblGroupDetail.getColumnCount(); i++) {
            column = tblGroupDetail.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(300);
            } else if (i == 1) {
                column.setPreferredWidth(300);
            }
        }
    }

    private void selectClientWiseGroups() {
        if (listClientGroups.isEmpty()) {
            List<ClientWiseCPTGroup> list = new ArrayList();
            list.add(new ClientWiseCPTGroup());
            tblGroupNames.setModel(new ClientWisePackagesTableModel(list));
        } else {
            tblGroupNames.setModel(new ClientWisePackagesTableModel(listClientGroups));
            ListSelectionModel selectionModel = tblGroupNames.getSelectionModel();
            tblGroupNames.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            setClientWiseGroupsColumnsWidths();
            selectionModel.setSelectionInterval(0, 0);
            Constants.tablelook.setJTableEnvironment(tblGroupNames);
            objPkg = listClientGroups.get(0);
            listClientGroupCPT = ctlClientCPTPackage.selectClientWisePackageDetail(objPkg.getPackageId(), "");
            selectClientWiseGroupDetail();
        }

    }

    private void setClientWiseGroupsColumnsWidths() {
        TableColumn column = null;
        for (int i = 0; i < tblGroupNames.getColumnCount(); i++) {
            column = tblGroupNames.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(30);
            } else if (i == 1) {
                column.setPreferredWidth(80);
            } else if (i == 2) {
                column.setPreferredWidth(220);
            }
        }
    }

    private void selectClientWiseGroupDetail() {
        tblGroupDetail.setModel(new ClientWisePackagesDetailTableModel(listClientGroupCPT));
        ListSelectionModel selectionModel = tblGroupDetail.getSelectionModel();
        tblGroupDetail.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setClientWiseGroupsDetailColumnsWidths();
        selectionModel.setSelectionInterval(0, 0);
        Constants.tablelook.setJTableEnvironment(tblGroupDetail);
    }

    private void setClientWiseGroupsDetailColumnsWidths() {
        TableColumn column = null;
        for (int i = 0; i < tblGroupDetail.getColumnCount(); i++) {
            column = tblGroupDetail.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(30);
            } else if (i == 1) {
                column.setPreferredWidth(80);
            } else if (i == 2) {
                column.setPreferredWidth(220);
            }
        }
    }
}
